name: Deploy to Kubernetes

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

          script: |
            echo "Deploying new version..."

            kubectl set image deployment/ai-incident-deployment \
            ai-incident-manager=aditya0910/ai-powered-incident-manager-app:${{ github.sha }} \
            -n ai-incident-namespace

            kubectl rollout status deployment/ai-incident-deployment \
            -n ai-incident-namespace

            echo "Deployment completed successfully!"